### ISSUE TITLE
Syntools

### ISSUE THREAD

**Issue by dsbarry** [Sarabveer/Synergy-Tools#3]
hello veer, sarabveer,

i'm running a dedicated synergy server, with hl ep1 ep2 and lost.

i downloaded the syntools zipfile, and located the place where to put it.

when starting the synergy server it gives me the following errors:

Unknown command "hyperspawn"
Unknown command "hyperspawn_time"
Unknown command "hyperspawn_teleport"
Unknown command "hyperspawn_carcheck"
Unknown command "hyperspawn_one_alive"
Unknown command "starthealth"
Unknown command "starthealth_value"
Unknown command "unvac_mode"
Unknown command "unvac_fix_insecure"
Unknown command "sm_cvar"

and the chatcommand !menu is not working.

i might have put the files in the zip file in the wrong location?

can you specify the location for the metamod/sourcemod and unvac folders ?

thank you so much! (dsbarry, the netherlands )

**Comment by Sarabveer** [comment]
Looks like you don't have SourceMod Installed.

**Comment by dsbarry** [comment]
that's correct, i didnt had it installed :) it works now! even though there are some minor bugs
for example, if you select vote car in the !menu, it showed /votecar in the server console, 
but it had to be !votecar, so i fixed that in the cfg,

- will you help me with another question? that is ;
you CAN go into the mapvote menu, but you cannot select a map, it just does not respond on pressed keys, and sometimes it DOES and then it says "[sm] you do not have access to this command" 
i have no clue how to fix that

 i can't thank you enough!
you've been a great help!

**Comment by Sarabveer** [comment]
You need to setup SoureceMod admins/permissions

Also, I will be closing this issue since it is not an issue with SynTools
